language: python
python:
  - "3.9"
install:
  - pip install -r requirements_ci.txt
script:
  - python -m compileall pykerio
  - python -m pycodestyle pykerio
  - python -m flake8 pykerio
  - python -m build --outdir=dist .
  - python -m pip install --verbose dist/*.whl
  - python -m pip list
  - python -m pip freeze
  - ls -laR .
  - python -m pip uninstall --yes --verbose pykerio
  - python -m pytest --verbose --capture=no tests/enums
# Disabled interfaces as actually the demo server is not reachable anymore
# - python -m pytest --verbose --capture=no tests/interfaces
  - python -m pytest --verbose --capture=no tests/lists
  - python -m pytest --verbose --capture=no tests/structs
  - python -m pytest --verbose --capture=no tests/types
